version: '3'

services:
  api:
    build: 
      context: .
      dockerfile: Dockerfile
    # -bを省略するとホストからコンテナにアクセスできない
    # -b 0.0.0.0を指定することで、コンテナが持つ全てのインターフェースでlistenできるようになるため、ホスト側からコンテナにアクセスできるようになる
    command: bundle exec rails s -p 3000 -b '0.0.0.0'
    ports:
      - '3000:3000'
    depends_on:
      - db
    volumes:
      - .:/app
      - bundle:/app/vendor/bundle
      # exclude volumes
      - /app/tmp
      - /app/log
      - /app/.git
    tty: true
    stdin_open: true
    env_file:
      - .env

  db:
    image: postgres:12.7-alpine
    volumes:
      - postgres:/var/lib/postgresql/data
    environment:
      POSTGRES_HOST_AUTH_METHOD: 'trust'
      POSTGRES_PASSWORD: 'postgres' # 立ち上げには必要だったが、後から変える
    env_file:
      - .env
    ports:
      - '3306:3306'

volumes:
  postgres:
  # bundleをマウントすることでGemの追加がdocker-compose run api bundle installで済む
  bundle: